In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error, mean_squared_error
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor

In [2]:
Med = pd.read_csv(r"C:\Users\SURFACE\Downloads\Maternal Health Risk Data Set.csv")

In [3]:
Med.head()

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [4]:
Med.tail()

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

In [6]:
Med.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          1014 non-null   int64  
 1   SystolicBP   1014 non-null   int64  
 2   DiastolicBP  1014 non-null   int64  
 3   BS           1014 non-null   float64
 4   BodyTemp     1014 non-null   float64
 5   HeartRate    1014 non-null   int64  
 6   RiskLevel    1014 non-null   object 
dtypes: float64(2), int64(4), object(1)
memory usage: 55.6+ KB


In [10]:
Med.isnull().sum()

Age            0
SystolicBP     0
DiastolicBP    0
BS             0
BodyTemp       0
HeartRate      0
RiskLevel      0
dtype: int64

In [19]:
Med.columns

Index(['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'BodyTemp', 'HeartRate',
       'RiskLevel'],
      dtype='object')

In [12]:
Med.Age.unique()

array([25, 35, 29, 30, 23, 32, 42, 19, 20, 48, 15, 50, 10, 40, 21, 18, 16,
       22, 49, 28, 12, 60, 55, 45, 31, 17, 26, 54, 44, 33, 13, 34, 38, 39,
       63, 14, 37, 51, 62, 43, 65, 66, 56, 70, 27, 36, 59, 24, 41, 46],
      dtype=int64)

In [13]:
Med.SystolicBP.unique()

array([130, 140,  90, 120,  85, 110,  70, 100,  75,  95,  76,  80, 115,
       135, 160, 129,  83,  99,  78], dtype=int64)

In [14]:
Med["DiastolicBP"].unique()

array([ 80,  90,  70,  85,  60,  89,  75, 100,  50,  65,  95,  49,  63,
        69,  76,  68], dtype=int64)

In [16]:
Med.BS.unique()

array([15.  , 13.  ,  8.  ,  7.  ,  6.1 ,  7.01, 11.  ,  6.9 , 18.  ,
        6.7 ,  7.5 ,  7.2 ,  7.1 ,  6.4 ,  9.  ,  6.  ,  7.7 , 12.  ,
       16.  ,  7.8 ,  6.8 ,  7.9 , 17.  , 19.  , 10.  ,  6.3 ,  6.6 ,
        6.5 ,  7.6 ])

In [41]:
Med.Age.value_counts()

Age
23    71
19    67
17    63
15    60
35    50
25    48
32    48
22    45
50    43
29    40
21    38
40    37
55    37
12    35
60    34
30    30
28    28
48    26
42    23
20    22
31    22
18    19
16    16
54    12
13    12
27     9
49     9
45     9
37     6
33     5
34     5
43     5
10     4
36     4
39     4
24     3
65     3
44     3
14     3
26     3
63     2
38     2
59     2
62     1
51     1
66     1
56     1
70     1
41     1
46     1
Name: count, dtype: int64

In [48]:
def fahrenheit_to_celsius(fahrenheit):
    return(fahrenheit - 32) *5.0 / 9.0

Med ["BodyTemp"] = Med["BodyTemp"].apply (fahrenheit_to_celsius)

In [49]:
Med.head()

Age  SystolicBP  DiastolicBP    BS   BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0  36.666667         86  high risk
1   35         140           90  13.0  36.666667         70  high risk
2   29          90           70   8.0  37.777778         80  high risk
3   30         140           85   7.0  36.666667         70  high risk
4   35         120           60   6.1  36.666667         76   low risk

In [50]:
Med['RiskLevel'] = Med['RiskLevel'].replace('low risk', 0)
Med['RiskLevel'] = Med['RiskLevel'].replace('mid risk', 1)
Med['RiskLevel'] = Med['RiskLevel'].replace('high risk', 2)

In [51]:
Med.head()

Age  SystolicBP  DiastolicBP    BS   BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0  36.666667         86          2
1   35         140           90  13.0  36.666667         70          2
2   29          90           70   8.0  37.777778         80          2
3   30         140           85   7.0  36.666667         70          2
4   35         120           60   6.1  36.666667         76          0

In [52]:
Med.corr()

Age  SystolicBP  DiastolicBP        BS  BodyTemp  HeartRate  \
Age          1.000000    0.416045     0.398026  0.473284 -0.255323   0.079798   
SystolicBP   0.416045    1.000000     0.787006  0.425172 -0.286616  -0.023108   
DiastolicBP  0.398026    0.787006     1.000000  0.423824 -0.257538  -0.046151   
BS           0.473284    0.425172     0.423824  1.000000 -0.103493   0.142867   
BodyTemp    -0.255323   -0.286616    -0.257538 -0.103493  1.000000   0.098771   
HeartRate    0.079798   -0.023108    -0.046151  0.142867  0.098771   1.000000   
RiskLevel    0.267225    0.396473     0.346649  0.569942  0.163984   0.194312   

             RiskLevel  
Age           0.267225  
SystolicBP    0.396473  
DiastolicBP   0.346649  
BS            0.569942  
BodyTemp      0.163984  
HeartRate     0.194312  
RiskLevel     1.000000

In [54]:
Med = pd.DataFrame(['Age'])

In [62]:
Age = np.array([25, 35, 29, 30, 23, 32, 42, 19, 20, 48, 15, 50, 10, 40, 21, 18, 16,
       22, 49, 28, 12, 60, 55, 45, 31, 17, 26, 54, 44, 33, 13, 34, 38, 39,
       63, 14, 37, 51, 62, 43, 65, 66, 56, 70, 27, 36, 59, 24, 41, 46])

In [65]:
bins = [0,10,15,20,25,30,35,40,45,50,55,100]
labels = ["0-17", "18-24", "25-34", "35-44","45-54", "55+"]

In [66]:
Age_groups = np.digitize(Age, bins = bins)
Age_groups = [labels[i-1] for i in Age_groups]

IndexError: list index out of range